# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(default=0, help_text='Enter the serving size', max_length=200),
        ),
    ]
